server:
  port: 8090
  
spring:
  datasource:
      driver-class-name: com.sybase.jdbc4.jdbc.SybDataSource
      url: jdbc:sybase:Tds:10.25.193.57:5000/xinterim
      username: developers
      password: developers@123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true